### ISSUE TITLE
KEYBASE

### ISSUE THREAD

**Issue by skorasaurus** [skorasaurus/skorasaurus.github.io#1]
NOTE To self, get keybase invite.

**Comment by KevinPayravi** [comment]
Still need one? :)

**Comment by skorasaurus** [comment]
hi, if you have one, that would be great, although I don't know anyone else it who has one ;) They've been rolling it quietly from what I hear. email is my github user name at gmail

**Comment by KevinPayravi** [comment]
Sent! :) I don't really know anyone either, other than a couple classmates and some more popular figures in the college hackathon community...great site to have a profile on nonetheless!
